### ISSUE TITLE
Full screen clock

### ISSUE THREAD

**Issue by aerozoic** [rparkins999/AndroidSecondsClockWidget#11]
Running the full screen clock does not prevent the screen timeout.

Android 12
Nokia G20

**Comment by rparkins999** [comment]
That is deliberate. The intention of the full screen clock is to be a bedside clock, connected to a charger, since most people charge their phone overnight when they aren't using it. So the full screen clock will keep the screen on if the device is connected to a charger. I do sometimes use the full screen clock to show the time so I can set the other clocks in my house, but I don't need it to be on for very long for that purpose.

I could add an option to make the full screen clock stay on if the device is not connected to a charger, but I'm reluctant to do that because I think it's a dangerous option. If you leave the screen on, and the clock updating every second, you will drain the battery if it is left to run all night while the device isn't connected to a charger. Giving your user battery draining options is generally a bad idea.

You can double tap the screen to turn it on again if your phone has that feature and it is enabled. [https://www.techmesto.com/set-up-double-tap-to-wake-screen-on-nokia-android-phones](https://www.techmesto.com/set-up-double-tap-to-wake-screen-on-nokia-android-phones) will tell you how to enable it on a Nokia phone.
