### ISSUE TITLE
Lock screen clock

### ISSUE THREAD

**Issue by lucas-mior** [rparkins999/AndroidSecondsClockWidget#13]
Hello, this app is awesome. I just wish it had also an option to add a lock screen clock. The default ones I can configure in my android miss the seconds. Can it be done?

**Comment by rparkins999** [comment]
I'm glad you like it. A lockscreen widget could probably be done, but I think updating it every second would use too much battery power. Currently the full screen version doesn't keep the screen on unless it's connected to a charger, in order to avoid draining the battery. Making a lockscreen widget which turns itself off after a while if it isn't connected to a charger is a bit more complicated.


    On Thursday, 30 May 2024 at 17:13:56 BST, Lucas Mior ***@***.***> wrote:  
 
 


Hello, this app is awesome. I just wish it had also an option to add a lock screen clock. The default ones I can configure in my android miss the seconds. Can it be done?

**Comment by lucas-mior** [comment]
Shouldn't the clock (as well as any other widget) on the lock screen stop running when the screen is off? I would like it either way. Also, there could be a quick setting to enable it only when you will use it.

**Comment by rparkins999** [comment]
From the Android Documentation at
https://developer.android.com/develop/ui/views/appwidgets
"Declares whether your widget can be displayed on the home screen (home_screen), the lock screen (keyguard), or both. For Android 5.0 and higher, only home_screen is valid."
It seems that lock screen widgets are no longer supported. I don't know how the built-in lock screen clock does it, but it's a system application and allowed to do things which a user-written app can't do.
It might be possible to display a lock screen notification and update it every second, but that would be a whole new ball game, not a simple modification.


    On Thursday, 30 May 2024 at 21:12:06 BST, Lucas Mior ***@***.***> wrote:  
 
 


Shouldn't the clock (as well as any other widget) on the lock screen stop running when the screen is off? I would like it either way. Also, there could be a quick setting to enable it only when you will use it.

**Comment by lucas-mior** [comment]
Thank you for looking into it.
