### ISSUE TITLE
Cannot add widget

### ISSUE THREAD

**Issue by RigacciOrg** [rparkins999/AndroidSecondsClockWidget#14]
On my Android 13 with Lawnchair 14.Beta2 launcher I cannot add the widget. When configuring the home screen, tap "add widget": the SecondsClock app is not listed as a widget provider.

**Comment by rparkins999** [comment]
It's difficult to identify the problem from the limited information that you provide. I presume that Lawnchair is some third party home screen that you are using instead of the home screen provided by your device manufacturer: I have no way of knowing how it decides which applications, if any, are allowed to create widgets. Can you create widgets from other applications? If so, can you create widgets from some open source application whose manifest I can compare with mine?

From where did you get the version of SecondsClock that you are using? Fdroid? Built version from rparkins999/AndroidSecondsClock? Built yourself from the sources at rparkins999/AndroidSecondsClock? If you built it yourself, what build system did you use?

Does SecondsClock run if you tap the icon on the Applicatons screen which shows all your apps? If so, please provide the build details at the top of the main menu screen. Do the buttons on the main menu screen work? Does the full screen clock run if you touch the button for it? Does the Configure new widget button bring up the top level widget configuration page? If so please try changing something from the defaults and touching DONE to save your changes. Can you create a widget after doing that?

If you long press the SecondsClock icon on the Applicatons screen, does it offer to create a widget? If you can create a widget that way, the problem is in your home acreen launcher and nothing to do with my app.

What device are you running SecondsClock on? Do you have another device with a standard home screen, and if so can SecondsClock create widgets on that? Of course it works on my device (Samsung Galaxy S21 Ultra 5G with standard Samsung oneUI home screen running Android 12) and on the Android Studio emulator, otherwise I wouldn't have published it.

Those are the only devices that I have to test on. I'm not a commercial developer and I don't have a whole range of devices to test on, otherwise I wouldn't be giving apps away for free. I do my best to fix any bugs, but I can't support an arbitrary range of configurations.

**Comment by RigacciOrg** [comment]
I investigated further and I discovered that I was not able to install ANY widgets at all. Newly installed apps do not appear as widget providers!
It turned out to be a problem of where the app is installed. If the app is installed into the SD card it cannot be a widget provider, if I change the storage to phone internal memory, the problem is fixed (Settings => Storage => SD card => App => Change).
